### ISSUE TITLE
Can't install with node 0.11.14

### ISSUE THREAD

**Issue by Globegitter** [waterlock/waterlock-local-auth#10]
When trying to install on node 0.11.14 I am getting the following errors:

``` js
hild_process: customFds option is deprecated, use stdio instead.
2014-11-14 14:30:21.915 xcodebuild[88341:1908175] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc:54:18: error: no member named 'Dispose' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        callback.Dispose();
        ~~~~~~~~ ^
../src/bcrypt_node.cc:128:19: error: unknown type name 'uv_work_t'
void GenSaltAsync(uv_work_t* req) {
                  ^
../src/bcrypt_node.cc:137:24: error: unknown type name 'uv_work_t'
void GenSaltAsyncAfter(uv_work_t* req) {
                       ^
../src/bcrypt_node.cc:138:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/bcrypt_node.cc:146:44: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::Error(String::New(baton->error.c_str()));
                                   ~~~~~~~~^
../src/bcrypt_node.cc:147:19: error: no matching function for call to 'Undefined'
        argv[1] = Undefined();
                  ^~~~~~~~~
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/bcrypt_node.cc:150:19: error: no matching function for call to 'Undefined'
        argv[0] = Undefined();
                  ^~~~~~~~~
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/bcrypt_node.cc:156:20: error: member reference type 'v8::Persistent<v8::Function>' is not a pointer; maybe you meant to use '.'?
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
    ~~~~~~~~~~~~~~~^~
                   .
../src/bcrypt_node.cc:156:22: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
    ~~~~~~~~~~~~~~~  ^
../src/bcrypt_node.cc:156:36: error: no member named 'GetCurrent' in 'v8::Context'
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
                          ~~~~~~~~~^
../src/bcrypt_node.cc:164:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> GenerateSalt(const Arguments &args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/bcrypt_node.cc:165:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/bcrypt_node.cc:167:13: error: member access into incomplete type 'const v8::internal::Arguments'
    if (args.Length() < 3) {
            ^
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/bcrypt_node.cc:168:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("3 arguments expected")));
                                                   ~~~~~~~~^
../src/bcrypt_node.cc:171:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Object>()) != 16) {
                             ~~~~^~
../src/bcrypt_node.cc:171:61: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Object>()) != 16) {
                                                        ~~~~^~
../src/bcrypt_node.cc:171:68: error: 'Object' does not refer to a value
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Object>()) != 16) {
                                                                   ^
/var/folders/_r/r2p1fv_n05b8j51sccfpm34w0000gp/T/.node-gyp/0.11.14/deps/v8/include/v8.h:2091:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/bcrypt_node.cc:171:76: error: expected expression
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Object>()) != 16) {
                                                                           ^
../src/bcrypt_node.cc:172:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Second argument must be a 16 byte Buffer")));
                                                   ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1


gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Projects/project/server/node_modules/waterlock-local-auth/node_modules/bcrypt
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "waterlock-local-auth" "--save"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

Switching back to node 0.10.x and all works fine. Is the issue with bcrypt not being compatible with node 0.11.x? Or anything else?

**Comment by pzontrop** [comment]
same with node v0.12.0
```
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc:54:18: error: no member named 'Dispose' in
      'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
        callback.Dispose();
        ~~~~~~~~ ^
../src/bcrypt_node.cc:128:19: error: unknown type name 'uv_work_t'
void GenSaltAsync(uv_work_t* req) {
                  ^
../src/bcrypt_node.cc:137:24: error: unknown type name 'uv_work_t'
void GenSaltAsyncAfter(uv_work_t* req) {
                       ^
../src/bcrypt_node.cc:138:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/pascal/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/bcrypt_node.cc:146:44: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::Error(String::New(baton->error.c_str()));
                                   ~~~~~~~~^
../src/bcrypt_node.cc:147:19: error: no matching function for call to
      'Undefined'
        argv[1] = Undefined();
                  ^~~~~~~~~
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/bcrypt_node.cc:150:19: error: no matching function for call to
      'Undefined'
        argv[0] = Undefined();
                  ^~~~~~~~~
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/bcrypt_node.cc:156:20: error: member reference type
      'v8::Persistent<v8::Function>' is not a pointer; maybe you meant to use
      '.'?
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
    ~~~~~~~~~~~~~~~^~
                   .
../src/bcrypt_node.cc:156:22: error: no member named 'Call' in
      'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
    ~~~~~~~~~~~~~~~  ^
../src/bcrypt_node.cc:156:36: error: no member named 'GetCurrent' in
      'v8::Context'
    baton->callback->Call(Context::GetCurrent()->Global(), 2, argv);
                          ~~~~~~~~~^
../src/bcrypt_node.cc:164:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> GenerateSalt(const Arguments &args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/bcrypt_node.cc:165:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/bcrypt_node.cc:167:13: error: member access into incomplete type 'const
      v8::internal::Arguments'
    if (args.Length() < 3) {
            ^
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/bcrypt_node.cc:168:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("3 argume...
                                                   ~~~~~~~~^
../src/bcrypt_node.cc:171:34: error: type 'const v8::internal::Arguments' does
      not provide a subscript operator
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Objec...
                             ~~~~^~
../src/bcrypt_node.cc:171:61: error: type 'const v8::internal::Arguments' does
      not provide a subscript operator
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Objec...
                                                        ~~~~^~
../src/bcrypt_node.cc:171:68: error: 'Object' does not refer to a value
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Objec...
                                                                   ^
/Users/xxxx/.node-gyp/0.12.0/deps/v8/include/v8.h:2110:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/bcrypt_node.cc:171:76: error: expected expression
    if (!Buffer::HasInstance(args[1]) || Buffer::Length(args[1].As<Object>()) !...
                                                                           ^
../src/bcrypt_node.cc:172:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Second a...
                                                   ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxx/Code/lexiBexi/backend/node_modules/waterlock-local-auth/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "waterlock-local-auth"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

**Comment by kriswill** [comment]
it looks like you're trying to install bcrypt 0.7.8, which won't work with node 0.12.0.  you'll need bcrypt 0.8.1, which is the version specified in the package.json.

**Comment by kriswill** [comment]
My bad, it looks like that hasn't been published yet.  @Globegitter can you push a new version to NPM?

**Comment by pzontrop** [comment]
Exactly what happened. But apparently there was already an issue open for node 0.12.0
https://github.com/waterlock/waterlock-local-auth/issues/18
I also asked there to update the NPM registry.

**Comment by davidrivera** [comment]
@pzontrop sorry about that man, a lot of things we're happening, but now we're getting back on track.
