### ISSUE TITLE
build failing on sails lift

### ISSUE THREAD

**Issue by smartcris** [waterlock/waterlock-local-auth#29]
After a clean install of sails 0.11  + waterlock and manually adding waterlock-local-auth i get this error:

     C:\server\node_modules\waterlock\lib\methods.js:112
      throw error;
            ^
    Error: Authentication method waterlock-local-auth could not be found.
    Try running npm install waterlock-local-auth

    at Object._errorHandler (C:\server\node_modules\waterlock\lib\methods.js:109:19)
    at Object._handleObjects (C:\server\node_modules\waterlock\lib\methods.js:54:14)
    at Object.collect (C:\server\node_modules\waterlock\lib\methods.js:33:19)
    at new Waterlock (C:\server\node_modules\waterlock\lib\waterlock.js:19:50)
    at Object.<anonymous> (C:\server\node_modules\waterlock\lib\index.js:8:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\server\node_modules\waterlock\index.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by gunish** [comment]
when you will try to install npm install waterlock-local-auth, it will fail again, to get past this until the owner's fix this, use this command 

npm install git+https://github.com/gunish/waterlock-local-auth.git

**Comment by aars** [comment]
@gunish Could you make a PR out of that fix?

**Comment by Globegitter** [comment]
@smartcris can you please try again with the latest version `0.0.6`

**Comment by smartcris** [comment]
I'm able to install it correctly with npm (with few warnings related to bcrypt .....\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' a 'unsigned char'. Possibile loss of data....etc...), and sails is lifted.
