### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by gunish** [waterlock/waterlock-local-auth#30]
```
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/visahub/visahub-api/node_modules/waterlock-local-auth/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/visahub/visahub-api/node_modules/waterlock-local-auth/node_modules/bcrypt
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "waterlock-local-auth"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/visahub/visahub-api/npm-debug.log
```

**Comment by gunish** [comment]
For other's facing the same issue, I have created a form with a small fix (reverted the bcrypt) version to a previous version of the repository, please use the following command to get by 

npm install git+https://github.com/gunish/waterlock-local-auth.git

**Comment by aars** [comment]
@gunish Could you make a PR out of that fix?

**Comment by Globegitter** [comment]
@gunish please try the latest version `0.0.6`

**Comment by alkamin** [comment]
Still fails with `0.0.6`

**Comment by jamesdixon** [comment]
Has anyone figure this out? This bug is killing me. It seems to be random in a lot cases. Tried your repo @gunish, but no luck :-(

**Comment by wayne-o** [comment]
I've updated bcrypt to latest and also amended the target node versions in local-auth to match that of core and it seems to have fixed the issue: 

https://travis-ci.org/waterlock/waterlock-local-auth/builds/75943754

Please let me know if there are any further issues
